const testimonialsArray = [
  {
    name: "Anna K.",
    opinion: "Szybko, sprawnie i bez wychodzenia z domu! E-recepta przyszła w kilka minut.",
    date: "2025-07-01",
    stars: "★★★★★",
  },
  {
    name: "Michał Z.",
    opinion: "Bardzo profesjonalne podejście lekarzy. Polecam każdemu, kto ceni sobie czas.",
    date: "2025-06-28",
    stars: "★★★★☆",
  },
  {
    name: "Joanna P.",
    opinion: "Zwolnienie L4 otrzymałam tego samego dnia. Usługa naprawdę godna zaufania.",
    date: "2025-06-25",
    stars: "★★★★★",
  },
  {
    name: "Tomasz W.",
    opinion: "Lekarz był bardzo uprzejmy i pomocny. Wszystko przebiegło szybko i bezproblemowo.",
    date: "2025-06-22",
    stars: "★★★★☆",
  },
  {
    name: "Magdalena Z.",
    opinion: "E-recepta została wystawiona w ciągu kilku minut. Polecam tę usługę!",
    date: "2025-06-20",
    stars: "★★★★★",
  },
  {
    name: "Piotr S.",
    opinion: "Konsultacja była szybka i konkretna. Lekarz odpowiedział na wszystkie moje pytania.",
    date: "2025-06-18",
    stars: "★★★★☆",
  },
  {
    name: "Katarzyna M.",
    opinion: "Bardzo wygodna forma konsultacji. Nie musiałam wychodzić z domu.",
    date: "2025-06-15",
    stars: "★★★★★",
  },
  {
    name: "Adam R.",
    opinion: "Usługa działa bardzo sprawnie. Polecam każdemu, kto potrzebuje szybkiej pomocy.",
    date: "2025-06-12",
    stars: "★★★★☆",
  },
  {
    name: "Paulina T.",
    opinion: "Lekarz był bardzo profesjonalny. E-recepta została wystawiona błyskawicznie.",
    date: "2025-06-10",
    stars: "★★★★★",
  },
  {
    name: "Grzegorz J.",
    opinion: "Konsultacja online to świetne rozwiązanie. Wszystko przebiegło sprawnie.",
    date: "2025-06-08",
    stars: "★★★★☆",
  },
  {
    name: "Ewa R.",
    opinion: "Bardzo szybka obsługa. Lekarz był pomocny i uprzejmy.",
    date: "2025-06-05",
    stars: "★★★★★",
  },
  {
    name: "Sebastian C.",
    opinion: "Polecam tę usługę każdemu, kto potrzebuje szybkiej konsultacji lekarskiej.",
    date: "2025-06-03",
    stars: "★★★★☆",
  },
  {
    name: "Natalia J.",
    opinion: "E-recepta została wystawiona w ciągu kilku minut. Bardzo wygodne rozwiązanie.",
    date: "2025-06-01",
    stars: "★★★★★",
  },
  {
    name: "Łukasz W.",
    opinion: "Lekarz był bardzo kompetentny. Konsultacja przebiegła szybko i sprawnie.",
    date: "2025-05-30",
    stars: "★★★★☆",
  },
  {
    name: "Monika K.",
    opinion: "Bardzo polecam tę usługę. Lekarz był uprzejmy i pomocny.",
    date: "2025-05-28",
    stars: "★★★★★",
  },
  {
    name: "Jakub T.",
    opinion: "Konsultacja była szybka i konkretna. Polecam każdemu, kto ceni sobie czas.",
    date: "2025-05-25",
    stars: "★★★★☆",
  },
  {
    name: "Sylwia P.",
    opinion: "E-recepta została wystawiona błyskawicznie. Bardzo wygodne rozwiązanie.",
    date: "2025-05-22",
    stars: "★★★★★",
  },
  {
    name: "Mateusz P.",
    opinion: "Lekarz był bardzo kompetentny. Konsultacja przebiegła sprawnie.",
    date: "2025-05-20",
    stars: "★★★★☆",
  },
  {
    name: "Zuzanna B.",
    opinion: "Bardzo szybka obsługa. Lekarz odpowiedział na wszystkie moje pytania.",
    date: "2025-05-18",
    stars: "★★★★★",
  },
  {
    name: "Wojciech N.",
    opinion: "Polecam tę usługę każdemu, kto potrzebuje szybkiej pomocy lekarskiej.",
    date: "2025-05-15",
    stars: "★★★★☆",
  },
];